package gnb.jalgol.compiler.codegen;

import gnb.jalgol.compiler.SymbolTableBuilder;
import gnb.jalgol.compiler.antlr.AlgolParser;
import java.util.*;

/**
 * Manages the shared state and common utilities for the code generation process.
 */
public class ContextManager {
    private final String source;
    private final String packageName;
    private final String className;
    private Map<String, String> symbolTable;
    private Map<String, Integer> localIndex;
    private final Map<AlgolParser.ExprContext, String> exprTypes;
    private Map<String, int[]> arrayBounds;
    private final Map<String, SymbolTableBuilder.ProcInfo> procedures;
    
    // State for thunks and procedure blocks
    private final Map<String, String> thunkClasses = new LinkedHashMap<>();
    private final List<String> procMethods = new ArrayList<>();
    private int thunkId = 0;
    private int nextLocalIndex = 0;
    
    private boolean inProcedureDecl;
    private boolean inProcedureWalk;

    private String currentProcName;
    private String currentProcReturnType;
    private int procRetvalSlot;
    private Map<String, int[]> mainArrayBounds;

    private final StringBuilder mainCode = new StringBuilder();
    private final Deque<StringBuilder> outputStack = new ArrayDeque<>();
    private StringBuilder activeOutput;

    private Map<String, String> mainSymbolTable;

    public ContextManager(String source, String packageName, String className, Map<String, SymbolTableBuilder.ProcInfo> procedures, Map<AlgolParser.ExprContext, String> exprTypes) {
        this.source = source;
        this.packageName = packageName;
        this.className = className;
        this.procedures = procedures;
        this.exprTypes = exprTypes;
        this.activeOutput = mainCode;
        this.symbolTable = new HashMap<>();
        this.localIndex = new HashMap<>();
    }

    public void setMainContext(Map<String, String> symbolTable, Map<String, Integer> localIndex, int numLocals, Map<String, int[]> arrayBounds) {
        this.symbolTable = symbolTable;
        this.localIndex = localIndex;
        this.nextLocalIndex = numLocals;
        this.arrayBounds = arrayBounds;
    }

    public void pushOutput(StringBuilder sb) {
        outputStack.push(activeOutput);
        activeOutput = sb;
    }

    public void popOutput() {
        if (!outputStack.isEmpty()) {
            activeOutput = outputStack.pop();
        }
    }

    public StringBuilder getActiveOutput() {
        return activeOutput;
    }

    public void addProcedureMethod(String methodCode) {
        procMethods.add(methodCode);
    }

    public void addThunkClass(String classCode) {
        String className = "Thunk" + thunkId; // This is a bit loose but works for now
        thunkClasses.put(className, classCode);
    }

    public void saveMainContext() {
        this.mainSymbolTable = new HashMap<>(symbolTable);
    }

    public void restoreMainContext() {
        this.symbolTable = mainSymbolTable;
    }

    public String finalizeAssembly() {
        StringBuilder full = new StringBuilder();
        // The header is now generated by CodeGenerator enterProgram
        // and appended directly to activeOutput (mainCode)
        for (String pm : procMethods) full.append(pm).append("\n");
        full.append(mainCode);
        return full.toString();
    }

    public Map<String, String> getThunkClasses() { return thunkClasses; }
    public List<String> getProcMethods() { return procMethods; }

    public void setProcedureContext(String name, String returnType, int retvalSlot) {
        this.currentProcName = name;
        this.currentProcReturnType = returnType;
        this.procRetvalSlot = retvalSlot;
    }

    public String getCurrentProcName() { return currentProcName; }
    public String getCurrentProcReturnType() { return currentProcReturnType; }
    public int getProcRetvalSlot() { return procRetvalSlot; }

    public String getPackageName() { return packageName; }
    public String getClassName() { return className; }
    public Map<String, String> getSymbolTable() { return symbolTable; }
    public void setSymbolTable(Map<String, String> st) { this.symbolTable = st; }
    public Map<String, Integer> getLocalIndex() { return localIndex; }
    public void setLocalIndex(Map<String, Integer> li) { this.localIndex = li; }
    public Map<AlgolParser.ExprContext, String> getExprTypes() { return exprTypes; }
    public Map<String, int[]> getArrayBounds() { return arrayBounds; }
    public void setArrayBounds(Map<String, int[]> ab) { this.arrayBounds = ab; }
    public Map<String, SymbolTableBuilder.ProcInfo> getProcedures() { return procedures; }
    public Map<String, String> getMainSymbolTable() { return mainSymbolTable; }

    public int getThunkId() { return thunkId; }
    public void incrementThunkId() { thunkId++; }
    public int getNextLocalIndex() { return nextLocalIndex; }
    public void setNextLocalIndex(int n) { nextLocalIndex = n; }

    public boolean isInProcedureDecl() { return inProcedureDecl; }
    public void setInProcedureDecl(boolean b) { inProcedureDecl = b; }
    public boolean isInProcedureWalk() { return inProcedureWalk; }
    public void setInProcedureWalk(boolean b) { inProcedureWalk = b; }

    private int procRefId = 0;
    private final Map<String, String> procRefClasses = new LinkedHashMap<>();

    public int getProcRefId() { return procRefId; }
    public void incrementProcRefId() { procRefId++; }
    public void addProcRefClass(String name, String content) { procRefClasses.put(name, content); }
    public Map<String, String> getProcRefClasses() { return procRefClasses; }
}
